[package]
name = "repo"
version = "0.2.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
eyre = "0.6.12"
log = "0.4.27"
rand = "0.9.1"
tempfile = "3.20.0"
uuid = { version = "1.17.0", features = ["v4"] }
